[build-system]
requires = ['setuptools >= 73.0']
build-backend = 'setuptools.build_meta'

[tool.setuptools]
packages = ['lesley']

[tool.setuptools.dynamic]
version = {attr = 'lesley.__version__'}

[project]
name = 'lesley'
dynamic = ['version']
authors = [
    {name = 'M Iqbal Tawakal', email = 'mit.iqi@gmail.com'}
]
description = 'Lesley is a lightweight Python package designed to create interactive, github-style, calendar-based heatmaps using altair.'
readme = 'README.md'
requires-python = '>=3.11'
license = 'MIT'
classifiers = [
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.11',
    'Programming Language :: Python :: 3.12',
    'Programming Language :: Python :: 3.13',
    'Programming Language :: Python :: 3.14',
    'Operating System :: OS Independent',
]
dependencies = [
    'altair==6.2.2',
    'pandas==3.0.5',
    'numpy==2.4.6; python_version < "3.12"',
    'numpy==2.5.2; python_version >= "3.12"',
    'matplotlib==3.11.1',
]

keywords = [ 
    'heatmap',
    'visualisation',
    'calendar',
    'daily',
    'matplotlib',
    'github plot',
    'month plot',
    'date plot',
    'plot',
    'plotting'
]

[project.optional-dependencies]
dev = [
    'pytest==9.1.1',
    'pytest-cov==7.1.0',
]

[project.urls]
Repository = 'https://github.com/mitbal/lesley.git'

[tool.pytest.ini_options]
pythonpath = ["."]
